Clean up getdir* usages in sh/*

diff --git a/src/sh/bspwm/util/bspwmpad b/src/sh/bspwm/util/bspwmpad
--- a/src/sh/bspwm/util/bspwmpad
+++ b/src/sh/bspwm/util/bspwmpad
@@ -1,5 +1,5 @@
 #!/usr/bin/env sh
-# 
+#
 # For optimum operation, include
 # ```
 # seq 0 9 | while IFS= read -r i; do
@@ -7,7 +7,7 @@
 # done
 # ```
 # in your `bspwmrc`.
-# 
+#
 # bspwm is not required for operation, but the script was designed with it in mind.
 
 execname="${0##*/}"
@@ -84,7 +84,7 @@ parseargs() {
                 done
             else
                 opt="${1#??}"
-                
+
                 case "$opt" in
                     directory   )
                         shift
@@ -161,8 +161,8 @@ handlenode() {
 }
 
 main() {
-    lckdir="$(getdir bspwmpadlck)" || {
-        printf "[ERROR]: getdir failed, aborting.\n"
+    lckdir="$(getdirsafe bspwmpadlck)" || {
+        printf "[ERROR]: getdirsafe failed, aborting.\n"
         exit 1
     }
 
@@ -179,7 +179,7 @@ main() {
         fi
     }
 
-    lck="$( 
+    lck="$(
         printf "%s\n" "${optnumber:-"$(seq 1 9)"}" | while IFS= read -r i; do
             mkdir -- "$lckdir/$i" 2> /dev/null && {
                 printf "%s" "$i"
diff --git a/src/sh/wow/wowsim b/src/sh/wow/wowsim
--- a/src/sh/wow/wowsim
+++ b/src/sh/wow/wowsim
@@ -12,7 +12,7 @@ ynq() {
 menu="$(getmenu)"
 
 if ynq "Use a simulation template?"; then
-    tfl="$(selfl -aRl 20 "$(getdir wowsimt)" | head -n 1)"
+    tfl="$(selfl -aRl 20 "$(getdirsafe wowsimt)" | head -n 1)"
 
     armory="$(grep "^\s*armory=.*" "$tfl" | tail -n 1 | sed 's/^\s*armory=//')"
 
@@ -26,8 +26,8 @@ if ynq "Use a simulation template?"; then
 
     simcargs="'$tfl'"
 else
-    simloc="$(getdir wowsimt)" || {
-        printf "[ERROR]: getdir failed, aborting.\n"
+    simloc="$(getdirsafe wowsimt)" || {
+        printf "[ERROR]: getdirsafe failed, aborting.\n"
         exit 1
     }
 
@@ -40,7 +40,7 @@ else
 
     screenname="simc-$selchar"
 
-    prevscreenname="$(screen -ls | grep ".$screenname-[0-9]\{10\}\s(Detached)")" 
+    prevscreenname="$(screen -ls | grep ".$screenname-[0-9]\{10\}\s(Detached)")"
     [ "$prevscreenname" ] && \
         ynq "A simulation for $selchar already exists. Would you like to see its progress instead?" && {
         "$TERMINAL" -e screen -r "$(printf "%s" "$prevscreenname" \
@@ -57,7 +57,7 @@ else
     simcargs="'armory=$region,$realm,$selchar' 'calculate_scale_factors=$csf'"
 fi
 
-outfl="$(getdir "wowsimd")/$screenname.html"
+outfl="$(getdirsafe "wowsimd")/$screenname.html"
 screen -dmS "$screenname" sh -c "simc $simcargs 'html=$outfl'"
 
 pid="$(
