Add decat subcommand in and refactor ffmw

diff --git a/ffmw b/ffmw
--- a/ffmw
+++ b/ffmw
@@ -3,7 +3,7 @@
 # TODO: Add cut and compress subcommands.
 # TODO: ffmw might fail to work with symlink infiles for the concat and split subcommands, test and if so fix.
 
-subcommands="concat help split trim"
+subcommands="concat decat help split trim"
 execname="${0##*/}"
 
 printhelp() {
@@ -12,6 +12,8 @@ printhelp() {
         concat)
             printf "%s\n" \
 "  concat [INFILE]... [OUTFILE]
+   Concatenate INFILEs into OUTFILE.
+
     -F COMMAND, --filter COMMAND
         Pass filenames through COMMAND before processing. If -s is not passed, the filenames will be passed in a file.
     -f, --force
@@ -27,18 +29,15 @@ printhelp() {
     -n, --no-clobber
         Do nothing if the output file exists.
     -r, --remove
-        Remove INFILE if concatenation succeeded.
+        Remove INFILE if operation succeeded.
     -s, --stdin
         Instead of passing filenames in a file, pass them from stdin to the filter command. This has no effect if -F is not passed."
             ;;
-        help)
+        decat)
             printf "%s\n" \
-"  help
-    All options are ignored."
-            ;;
-        split)
-            printf "%s\n" \
-"  split [INFILE] [OUTPATTERN] [PERIOD]
+"  decat [INFILE] [OUTPATTERN] [MARK]...
+   Decatenate INFILE at MARKs, naming the output files according to OUTPATTERN. OUTPATTERN only accepts %s and %d. MARKs should not contain the beginning or the ending of the INFILE. MARKs must be valid ffmpeg timestamps. Marks in floating point form are not accepted. Marks in timetamp form must have the minute and second field. Hour and millisecond fields are optional.
+
     -f, --force
         Overwrite the output file if it exists.
     -h, --help
@@ -52,11 +51,38 @@ printhelp() {
     --no-part-name
         Revert --part-name.
     -r, --remove
-        Remove INFILEs if concatenation succeeded."
+        Remove INFILE if operation succeeded."
+            ;;
+        help)
+            printf "%s\n" \
+"  help
+    All options are ignored."
+            ;;
+        split)
+            printf "%s\n" \
+"  split [INFILE] [OUTPATTERN] [PERIOD]
+   Split INFILE into PERIOD long chunks, naming the output files according to OUTPATTERN.
+
+    -f, --force
+        Overwrite the output file if it exists.
+    -h, --help
+        Print help message.
+    -i, --interactive
+        Prompt before overwriting the output file if it exists.
+    -n, --no-clobber
+        Do nothing if the output file exists.
+    -p, --part-name
+        Set OUTPATTERN to 'INFILE Part %d.mkv'. When this option is given, no OUTPATTERN is accepted.
+    --no-part-name
+        Revert --part-name.
+    -r, --remove
+        Remove INFILE if operation succeeded."
             ;;
         trim)
             printf "%s\n" \
 "  trim [INFILE] [OUTFILE]
+   Trim the black bars of INFILE and write the resultant to OUTFILE.
+
     -f, --force
         Overwrite the output file if it exists.
     -h, --help
@@ -70,7 +96,7 @@ printhelp() {
     -n, --no-clobber
         Do nothing if the output file exists.
     -r, --remove
-        Remove INFILE if concatenation succeeded."
+        Remove INFILE if operation succeeded."
             ;;
         *)
             printf "%s\n" \
@@ -255,6 +281,76 @@ $1"
 
             printf "%s" "$infls" | grep -Fxq -- "$outfl" && printferrq "OUTFILE cannot be included in INFILEs, exiting.\n"
             ;;
+        decat)
+            while [ -n "$1" ]
+            do
+                if [ "${1%"${1#?}"}" = "-" ]
+                then
+                    if ! [ "${1%"${1#??}"}" = "--" ]
+                    then
+                        sopt="$(printf "%s" "$1" | cut -c2-)"
+
+                        while [ -n "$sopt" ]
+                        do
+                            opt="$(printf "%s" "$sopt" | cut -c1)"
+
+                            case "$opt"
+                            in
+                                f) overwrite="-y";;
+                                h) printhelp "decat"; exit 0;;
+                                i) overwrite="";;
+                                n) overwrite="-n";;
+                                p) partname="1";;
+                                r) remove="1";;
+                                *) printusage "-$opt" "decat";;
+                            esac
+
+                            sopt="$(printf "%s" "$sopt" | cut -c2-)"
+                        done
+                    else
+                        opt="$(printf "%s" "$1" | cut -c3-)"
+                        
+                        case "$opt"
+                        in
+                            force         ) overwrite="-y";;
+                            help          ) printhelp "decat"; exit 0;;
+                            interactive   ) overwrite="";;
+                            no-clobber    ) overwrite="-n";;
+                            part-name     ) partname="1";;
+                            no-part-name  ) partname="0";;
+                            remove        ) remove="1";;
+                            ""            ) shift; break;;
+                            *             ) printusage "--$opt" "decat";;
+                        esac
+                    fi
+                else
+                    argv="$argv
+$1"
+                fi
+
+                shift
+            done
+
+            for i
+            do
+                argv="$argv
+$1"
+            done
+
+            argv="$(printf "%s" "$argv" | tail -n +2)"
+            infl="$(printf "%s\n" "$argv" | head -n 1)"
+
+            if [ "$partname" = "1" ]
+            then
+                [ "$(printf "%s\n" "$argv" | wc -l)" -lt 2 ] && printferrq "--part-name is given. At least 2 positional arguments are expected, exiting.\n"
+                outpat="%s Part %d.mkv"
+                marks="$(printf "%s\n" "$argv" | tail -n +2)"
+            else
+                [ "$(printf "%s\n" "$argv" | wc -l)" -lt 3 ] && printferrq "At least 3 positional arguments are expected, exiting.\n"
+                outpat="$(printf "%s\n" "$argv" | tail -n 2 | head -n 1)"
+                marks="$(printf "%s\n" "$argv" | tail -n +3)"
+            fi
+            ;;
         help)
             for i
             do
@@ -329,7 +425,7 @@ $1"
             if [ "$partname" = "1" ]
             then
                 [ "$(printf "%s\n" "$argv" | wc -l)" -ne 2 ] && printferrq "--part-name is given. Exactly 2 positional arguments are required and accepted, exiting.\n"
-                outpat="$infl Part %d.mkv"
+                outpat="$(rawname "$infl") Part %d.mkv"
             else
                 [ "$(printf "%s\n" "$argv" | wc -l)" -ne 3 ] && printferrq "Exactly 3 positional arguments are required and accepted, exiting.\n"
                 outpat="$(printf "%s\n" "$argv" | tail -n 2 | head -n 1)"
@@ -407,6 +503,16 @@ $1"
     esac
 }
 
+processargs() {
+    case "$cmd"
+    in
+        decat)
+            [ -n "$(printf "%s\n" "$marks" | sed -E '/^([0-9]+:)?[0-9]{2}:[0-9]{2}(.[0-9]{3})?$/d')" ] && printferrq "Some MARKs are invalid. See $execname --help.\n"
+            outpat="$(printf "%s" "$outpat" | sed 's/\([^%\\]*\)%s/\1'"$(rawname "$infl")"'/g')"
+            ;;
+    esac
+}
+
 concat() {
     lstfl="$(mktemp -p .)"
     trap 'rm -f -- "$lstfl"' HUP INT QUIT TERM
@@ -447,6 +553,25 @@ concat() {
     [ -f "$lstfl" ] && rm -f -- "$lstfl"
 }
 
+decat() {
+    $pperf ffmpeg -hide_banner $overwrite -i "$infl" -to "$(printf "%s\n" "$marks" | head -n 1)" -safe 0 -c copy "$(printf "%s" "$outpat" | sed 's/\([^%\\]*\)%d/\11/g')" || printferrq "ffmpeg failed, exiting.\n"
+
+    n=2
+    [ "$(printf "%s\n" "$marks" | wc -l)" -ne 1 ] && while IFS= read -r ss <&3 && IFS= read -r to <&4
+    do
+        $pperf ffmpeg -hide_banner $overwrite -i "$infl" -ss "$ss" -to "$to" -safe 0 -c copy "$(printf "%s" "$outpat" | sed 's/\([^%\\]*\)%d/\1'"$n"'/g')" || printferrq "ffmpeg failed, exiting.\n"
+        : $((n += 1))
+    done 3<<EOF1 4<<EOF2
+$(printf "%s\n" "$marks" | head -n -1)
+EOF1
+$(printf "%s\n" "$marks" | tail -n +2)
+EOF2
+
+    $pperf ffmpeg -hide_banner $overwrite -i "$infl" -ss "$(printf "%s\n" "$marks" | tail -n 1)" -safe 0 -c copy "$(printf "%s" "$outpat" | sed 's/\([^%\\]*\)%d/\1'"$n"'/g')" || printferrq "ffmpeg failed, exiting.\n"
+
+    [ "$remove" = "1" ] && rm -- "$infl"
+}
+
 help() {
     printhelp
 }
@@ -474,6 +599,7 @@ main() {
 }
 
 parseargs "$@"
+processargs
 
 qldiff=$((${#quiet} - ${#loud}))
 
