Add crop subcommand and fix bugs in ffmw

diff --git a/ffmw b/ffmw
--- a/ffmw
+++ b/ffmw
@@ -1,9 +1,9 @@
 #!/usr/bin/env sh
 # ffmpeg wrapper for actions I commonly use.
-# TODO: Add cut and compress subcommands.
+# TODO: Add rm (inverse of crop) and compress subcommands.
 # TODO: ffmw might fail to work with symlink infiles for the concat and split subcommands, test and if so fix.
 
-subcommands="concat decat help split trim"
+subcommands="concat crop decat help split trim"
 execname="${0##*/}"
 
 printhelp() {
@@ -23,15 +23,35 @@ printhelp() {
     -i, --interactive
         Prompt before overwriting the output file if it exists.
     -M, --move-to-first
-        Move OUTFILE to the first INFILE after concatenation is finished. First INFILE is computed after option -F is processed. This overrides -m if present.
+        Move OUTFILE to the first INFILE after the operation is finished. First INFILE is computed after option -F is processed. This overrides -m if present.
     -m MOVEFILE, --move-to MOVEFILE
-        Move OUTFILE to MOVEFILE after concatenation is finished. This is overridden by -M if present.
+        Move OUTFILE to MOVEFILE after the operation is finished. This is overridden by -M if present.
     -n, --no-clobber
         Do nothing if the output file exists.
     -r, --remove
         Remove INFILE if operation succeeded.
     -s, --stdin
         Instead of passing filenames in a file, pass them from stdin to the filter command. This has no effect if -F is not passed."
+            ;;
+        crop)
+            printf "%s\n" \
+"  crop [INFILE] [OUTFILE] [BEGINMARK] [ENDMARK]
+   crop INFILE according to BEGINMARK and ENDMARK and write the resultant to OUTFILE. BEGINMARK must be a timestamp in the format HH:MM:SS.sss, where hour and millisecond fields can be omitted. ENDMARK can be a timestamp or a duration. BEGINMARK or ENDMARK can be -, in which case they will respectively be treated as the beginning or the ending of INFILE.
+
+    -f, --force
+        Overwrite the output file if it exists.
+    -h, --help
+        Print help message.
+    -i, --interactive
+        Prompt before overwriting the output file if it exists.
+    -M, --move-to-original
+        Move OUTFILE to INFILE after the operation is finished. This overrides -m if present.
+    -m MOVEFILE, --move-to MOVEFILE
+        Move OUTFILE to MOVEFILE after the operation is finished. This is overridden by -M if present.
+    -n, --no-clobber
+        Do nothing if the output file exists.
+    -r, --remove
+        Remove INFILE if operation succeeded."
             ;;
         decat)
             printf "%s\n" \
@@ -90,13 +110,13 @@ printhelp() {
     -i, --interactive
         Prompt before overwriting the output file if it exists.
     -M, --move-to-original
-        Move OUTFILE to INFILE after concatenation is finished. This overrides -m if present.
+        Move OUTFILE to INFILE after the operation is finished. This overrides -m if present.
     -m MOVEFILE, --move-to MOVEFILE
-        Move OUTFILE to MOVEFILE after concatenation is finished. This is overridden by -M if present.
+        Move OUTFILE to MOVEFILE after the operation is finished. This is overridden by -M if present.
     -n, --no-clobber
         Do nothing if the output file exists.
     -r, --remove
-        Remove INFILE if operation succeeded."
+        Remove INFILE if the operation succeeded."
             ;;
         *)
             printf "%s\n" \
@@ -182,7 +202,7 @@ parseargs() {
                         l) loud="${loud}1";;
                         p) pperf="perf stat";;
                         q) quiet="${quiet}1";;
-                        t) shift; assertarg "-t" "COUNT" "$1"; threads="$1";;
+                        t) shift; assertarg "-t" "COUNT" "$1"; threads="-threads $1";;
                         *) printusage "-$opt";;
                     esac
 
@@ -198,7 +218,7 @@ parseargs() {
                     print-performance    ) pperf="perf stat";;
                     no-print-performance ) pperf="";;
                     quiet                ) quiet="${quiet}1";;
-                    threads              ) shift; assertarg "--threads" "COUNT" "$1"; threads="$1";;
+                    threads              ) shift; assertarg "--threads" "COUNT" "$1"; threads="-threads $1";;
                     *                    ) printusage "--$opt";;
                 esac
             fi
@@ -284,6 +304,99 @@ $1"
             [ "$(printf "%s\n" "$infls" | wc -l)" -lt 2 ] && printferrq "At least 2 in files and exactly one out file are required, exiting.\n"
 
             printf "%s" "$infls" | grep -Fxq -- "$outfl" && printferrq "OUTFILE cannot be included in INFILEs, exiting.\n"
+            ;;
+        crop)
+            while [ -n "$1" ]
+            do
+                [ "$1" = "-" ] && {
+                    argv="$argv
+$1"
+                    shift
+                    continue
+                }
+                if [ "${1%"${1#?}"}" = "-" ]
+                then
+                    if ! [ "${1%"${1#??}"}" = "--" ]
+                    then
+                        sopt="$(printf "%s" "$1" | cut -c2-)"
+
+                        while [ -n "$sopt" ]
+                        do
+                            opt="$(printf "%s" "$sopt" | cut -c1)"
+
+                            case "$opt"
+                            in
+                                f ) overwrite="-y";;
+                                h ) printhelp "crop"; exit 0;;
+                                i ) overwrite="";;
+                                M ) movefirst="1";;
+                                m ) shift; assertarg "-m" "MOVEFILE" "$1"; movefile="$1";;
+                                n ) overwrite="-n";;
+                                r ) remove="1";;
+                                * ) printusage "-$opt" "crop";;
+                            esac
+
+                            sopt="$(printf "%s" "$sopt" | cut -c2-)"
+                        done
+                    else
+                        opt="$(printf "%s" "$1" | cut -c3-)"
+                        
+                        case "$opt"
+                        in
+                            force            ) overwrite="-y";;
+                            help             ) printhelp "crop"; exit 0;;
+                            interactive      ) overwrite="";;
+                            move-to-original ) moveorig="1";;
+                            move-to          ) shift; assertarg "--move-to" "MOVEFILE" "$1"; movefile="$1";;
+                            no-clobber       ) overwrite="-n";;
+                            remove           ) remove="1";;
+                            ""               ) shift; break;;
+                            *                ) printusage "--$opt" "crop";;
+                        esac
+                    fi
+                else
+                    argv="$argv
+$1"
+                fi
+
+                shift
+            done
+
+            for i
+            do
+                argv="$argv
+$1"
+            done
+
+            argv="$(printf "%s" "$argv" | tail -n +2)"
+
+            [ "$(printf "%s\n" "$argv" | wc -l)" -ne 4 ] && printferrq "Exactly 4 positional arguments are required and accepted, exiting.\n"
+
+            infl="$(printf "%s\n" "$argv" | head -n 1)"
+            outfl="$(printf "%s\n" "$argv" | tail -n 3 | head -n 1)"
+            beginmark="$(printf "%s\n" "$argv" | tail -n 2 | head -n 1)"
+            endmark="$(printf "%s\n" "$argv" | tail -n 1)"
+
+            [ "$outfl" = "$infl" ] && printferrq "OUTFILE cannot be the same as INFILE, exiting.\n"
+            [ "$beginmark" = "-" ] && beginmark="0"
+
+            if [ "$endmark" = "-" ]
+            then
+                endmark=""
+            else
+                endmarkts="$(printf "%s\n" "$marks" | sed -E '/^([0-9]+:)?[0-9]{2}:[0-9]{2}(.[0-9]{3})?$/d')"
+                endmarkdur="$(printf "%s\n" "$marks" | sed -E '/^[0-9]+(\.[0-9]+)?$/d')"
+
+                if [ -n "$endmarkts" ]
+                then
+                    [ -n "$endmarkdur" ] && printferrq "ENDMARK must either be a timestamp or a duration.\n"
+                    endmark="-t $endmark"
+                else
+                    endmark="-to $endmark"
+                fi
+            fi
+
+            [ "$moveorig" = "1" ] && movefile="$infl"
             ;;
         decat)
             while [ -n "$1" ]
@@ -472,14 +585,14 @@ $1"
                         case "$opt"
                         in
                             force            ) overwrite="-y";;
-                            help             ) printhelp "concat"; exit 0;;
+                            help             ) printhelp "trim"; exit 0;;
                             interactive      ) overwrite="";;
                             move-to-original ) moveorig="1";;
                             move-to          ) shift; assertarg "--move-to" "MOVEFILE" "$1"; movefile="$1";;
                             no-clobber       ) overwrite="-n";;
                             remove           ) remove="1";;
                             ""               ) shift; break;;
-                            *                ) printusage "--$opt" "concat";;
+                            *                ) printusage "--$opt" "trim";;
                         esac
                     fi
                 else
@@ -505,6 +618,8 @@ $1"
 
 
             [ "$outfl" = "$infl" ] && printferrq "OUTFILE cannot be the same as INFILE, exiting.\n"
+
+            [ "$moveorig" = "1" ] && movefile="$infl"
             ;;
     esac
 }
@@ -539,14 +654,18 @@ concat() {
         exit 1
     }
 
-    [ "$remove" = "1" ] && printf "%s\n" "$infls" | while IFS= read -r i
-    do
-        rm -- "$i"
-    done
+    [ "$remove" = "1" ] && printf "%s\n" "$infls" | xargs rm --
 
     [ -n "$movefile" ] && mv ${overwrite:-"-i"} -- "$outfl" "$movefile"
 
     [ -f "$lstfl" ] && rm -f -- "$lstfl"
+}
+
+crop() {
+    $pperf ffmpeg -hide_banner $threads $overwrite -ss "$beginmark" -i "$infl" $endmark -safe 0 -c copy "$outfl" || printferrq "ffmpeg failed, exiting.\n"
+
+    [ "$remove" = "1" ] && rm -- "$infl"
+    [ -n "$movefile" ] && mv ${overwrite:-"-i"} -- "$outfl" "$movefile"
 }
 
 decat() {
@@ -555,7 +674,7 @@ decat() {
     n=2
     [ "$(printf "%s\n" "$marks" | wc -l)" -ne 1 ] && while IFS= read -r ss <&3 && IFS= read -r to <&4
     do
-        $pperf ffmpeg -hide_banner $threads $overwrite -i "$infl" -ss "$ss" -to "$to" -safe 0 -c copy "$(printf "%s" "$outpat" | sed 's/\([^%\\]*\)%d/\1'"$n"'/g')" || printferrq "ffmpeg failed, exiting.\n"
+        $pperf ffmpeg -hide_banner $threads $overwrite -ss "$ss" -i "$infl" -to "$to" -safe 0 -c copy "$(printf "%s" "$outpat" | sed 's/\([^%\\]*\)%d/\1'"$n"'/g')" || printferrq "ffmpeg failed, exiting.\n"
         : $((n += 1))
     done 3<<EOF1 4<<EOF2
 $(printf "%s\n" "$marks" | head -n -1)
@@ -563,7 +682,7 @@ EOF1
 $(printf "%s\n" "$marks" | tail -n +2)
 EOF2
 
-    $pperf ffmpeg -hide_banner $threads $overwrite -i "$infl" -ss "$(printf "%s\n" "$marks" | tail -n 1)" -safe 0 -c copy "$(printf "%s" "$outpat" | sed 's/\([^%\\]*\)%d/\1'"$n"'/g')" || printferrq "ffmpeg failed, exiting.\n"
+    $pperf ffmpeg -hide_banner $threads $overwrite -ss "$(printf "%s\n" "$marks" | tail -n 1)" -i "$infl" -safe 0 -c copy "$(printf "%s" "$outpat" | sed 's/\([^%\\]*\)%d/\1'"$n"'/g')" || printferrq "ffmpeg failed, exiting.\n"
 
     [ "$remove" = "1" ] && rm -- "$infl"
 }
@@ -580,8 +699,6 @@ split() {
 
 trim() {
     [ -f "$infl" ] || printferrq "No such file [%s], exiting.\n" "$infl"
-
-    [ "$moveorig" = "1" ] && movefile="$infl"
 
     $pperf ffmpeg -hide_banner $threads $overwrite -i "$infl" -vf "$(ffmpeg -hide_banner -ss 100 -i "$infl" -vframes 100 -vf cropdetect -f null - 2>&1 | grep "^.Parsed_cropdetect_0 @ 0x[0-9a-f].*crop=.*$" | awk '{print $NF}' | LC_ALL=C sort | LC_ALL=C uniq -c | LC_ALL=C sort -nr | head -n 1 | sed 's/^\s*[0-9]\+\s\+\(.*\)$/\1/')" -safe 0 -c:a copy "$outfl"
 
