Rewrite lckget

diff --git a/lckget b/lckget
--- a/lckget
+++ b/lckget
@@ -1,8 +1,6 @@
 #!/usr/bin/env sh
 
-lckfl="$(getfl "$1lck")" || {
-    printf "[ERROR]: getfl failed, aborting.\n"
-    exit 1
-}
-
-lck "$lckfl"
+for i
+do
+    lckfl="$(getfl "${i}lck")" && lck "$lckfl" || printf "Failed to acquire the lock [%s].\n" "$i" >&2
+done
