Modify behaviour of swp
Modified the behaviour of swp such that it will copy the smaller file to a temporary file, rather than copying the first given file, thus reducing the total disk space required.

diff --git a/swp b/swp
--- a/swp
+++ b/swp
@@ -24,11 +24,20 @@ check() {
 }
 
 swap() {
+    if [ "$( stat -c%s "$1" )" -lt "$( stat -c%s "$2" )" ]
+    then
+        tocopy="$1"
+        other="$2"
+    else
+        tocopy="$2"
+        other="$1"
+    fi
+
     tmp="$( mktemp )"
     [ "$tmp" = "" ] && echo "Could not create tmp file."
-    cp "$1" "$tmp" || { echo "Could not copy $1 to $tmp."; exit 1; }
-    cp "$2" "$1" || { echo "Could not copy $2 to $1. (tmp: $tmp)"; exit 1; }
-    cp "$tmp" "$2" || { echo "Could not copy $tmp to $2."; exit 1; }
+    cp "$tocopy" "$tmp" || { echo "Could not copy $tocopy to $tmp."; exit 1; }
+    cp "$other" "$tocopy" || { echo "Could not copy $other to $tocopy. (tmp: $tmp)"; exit 1; }
+    cp "$tmp" "$other" || { echo "Could not copy $tmp to $other."; exit 1; }
     rm "$tmp" || echo "Could not remove $tmp."
 }
 
