Edit swp
Add safety checks for non-existent files/directories, add safety checks for mixed files and directories, support single input calls by adding '_' at the end of the input.

diff --git a/swp b/swp
--- a/swp
+++ b/swp
@@ -1,16 +1,48 @@
 #!/usr/bin/env sh
 
-if [ "$3" ]
-then
-    echo "Only two arguments accepted."
-elif [ "$2" ]
-then
+check() {
+    isdir=0
+    for i in "$@"
+    do
+        [ -f "$i" -o -d "$i" ] || { 
+            echo "$i does not exist."
+            exit 1 
+        }
+        
+        [ -d "$i" ] && isdir=1
+    done
+
+    [ "$isdir" = "1" ] && {
+        for i in "$@"
+        do
+            [ -d "$i" ] || {
+                echo "Cannot swap a file and a directory."
+                exit 1
+            }
+        done
+    }
+}
+
+swap() {
     tmp="$( mktemp )"
     [ "$tmp" = "" ] && echo "Could not create tmp file."
     cp "$1" "$tmp" || { echo "Could not copy $1 to $tmp."; exit 1; }
     cp "$2" "$1" || { echo "Could not copy $2 to $1. (tmp: $tmp)"; exit 1; }
     cp "$tmp" "$2" || { echo "Could not copy $tmp to $2."; exit 1; }
     rm "$tmp" || echo "Could not remove $tmp."
+}
+
+if [ "$3" ]
+then
+    echo "At most two arguments are accepted."
+elif [ "$2" ]
+then
+    check "$1" "$2"
+    swap "$1" "$2"
+elif [ "$1" ]
+then
+    check "$1" "$1"_
+    swap "$1" "$1"_
 else
-    echo "Two arguments needed."
+    echo "At least one argument is needed."
 fi
