Vary exit code in update

diff --git a/update b/update
--- a/update
+++ b/update
@@ -46,6 +46,9 @@ lst="$( getfl upabl )" || {
     exit 1
 }
 
+errcount=0
+cmdcount=0
+
 while IFS= read -r i
 do
     [ "$( printf "%s" "$i" | sed -E 's/^\s*//' | cut -c1 )" = "#" ] && continue
@@ -65,8 +68,13 @@ do
     then
         log "Already up to date."
     else
-        eval "( $cmd )" || log "Failed to update $loc."
+        eval "( $cmd )" || {
+            log "Failed to update $loc."
+            : $(( err += 1 ))
+        }
     fi
+
+    : $(( cmdcount += 1 ))
 
     echo
 done < "$lst"
@@ -74,3 +82,8 @@ done < "$lst"
 rm "$lckfl"
 
 log "Done."
+
+exitcode=0
+[ "$errcount" -ne 0 ] && : $(( exitcode = cmdcount - errcount + 1 ))
+
+exit "$exitcode"
