Format execselapp, openass and steammgr & fix bug in steammgr
Fixed a bug in steammgr where a previous formatting broke a printf formatted string.

diff --git a/src/sh/hotkey/steammgr b/src/sh/hotkey/steammgr
--- a/src/sh/hotkey/steammgr
+++ b/src/sh/hotkey/steammgr
@@ -109,17 +109,20 @@ if [ -z "${sel##*<*>*}" ]; then
                 grep -E '\s*"[0-9]+"\s*".*"$' -- "$(getfl steamlibdirs)" \
                     | awk -F '"' '{print $4}' \
                     | while IFS= read -r i; do
-                    cd "$i/steamapps" || {
-                        printf "%s\n" "Could not cd into '$i/steamapps', passing."
-                        continue
-                    }
+                        cd "$i/steamapps" || {
+                            printf "%s\n" "Could not cd into '$i/steamapps', passing."
+                            continue
+                        }
 
-                    find '.' -mindepth 1 -maxdepth 1 -type f -name "*.acf" -printf '%P\n' \
-                        | while IFS= read -r j; do
-                        printf '%s\n' "$(grep '"appid"' -- "$j" | awk -F '"' '{print $4}') \
-                            $(grep '"name"' -- "$j" | awk -F '"' '{print $4}')"
-                    done
-                done | $menu -i -l 25 -p "Select game or enter game ID:" | awk '{print $1}'
+                        find '.' -mindepth 1 -maxdepth 1 -type f -name "*.acf" -printf '%P\n' \
+                            | while IFS= read -r j; do
+                                printf '%s\n' "$(
+                                    grep '"appid"' -- "$j" | awk -F '"' '{print $4}'
+                                ) $(
+                                    grep '"name"' -- "$j" | awk -F '"' '{print $4}'
+                                )"
+                            done
+                    done | $menu -i -l 25 -p "Select game or enter game ID:" | awk '{print $1}'
             )"
             ;;
         *) str="$($menu -l 0 -p "<$strtype>:" < /dev/null)";;
