Fail on invalid option in vpn and wallpaper

diff --git a/src/sh/hotkey/vpn b/src/sh/hotkey/vpn
--- a/src/sh/hotkey/vpn
+++ b/src/sh/hotkey/vpn
@@ -16,6 +16,7 @@ while getopts "hsv:" OPT; do
             ;;
         s) optstatus=1;;
         v) VPN="$OPTARG";;
+        *) printf "Invalid option given: %s\n" "$OPT"; exit 1;;
     esac
 done
 shift "$((OPTIND - 1))"
diff --git a/src/sh/init/wallpaper b/src/sh/init/wallpaper
--- a/src/sh/init/wallpaper
+++ b/src/sh/init/wallpaper
@@ -40,6 +40,7 @@ do
             esac
             optexec="$OPTARG"
             ;;
+        *) printf "Invalid option given: %s\n" "$OPT"; exit 1;;
     esac
 done
 shift "$((OPTIND - 1))"
