Migrate to getpath

diff --git a/src/sh/wow/wowsim b/src/sh/wow/wowsim
--- a/src/sh/wow/wowsim
+++ b/src/sh/wow/wowsim
@@ -12,7 +12,7 @@ ynq() {
 menu="$(getmenu)"
 
 if ynq "Use a simulation template?"; then
-    tfl="$(selfl -aRl 20 "$(getdirsafe wowsimt)" | head -n 1)"
+    tfl="$(selfl -aRl 20 "$(getpath -ds -- wowsimt)" | head -n 1)"
 
     armory="$(grep "^\s*armory=.*" "$tfl" | tail -n 1 | sed 's/^\s*armory=//')"
 
@@ -26,8 +26,8 @@ if ynq "Use a simulation template?"; then
 
     simcargs="'$tfl'"
 else
-    simloc="$(getdirsafe wowsimt)" || {
-        printf "[ERROR]: getdirsafe failed, aborting.\n"
+    simloc="$(getpath -ds -- wowsimt)" || {
+        printf "[ERROR]: getpath -ds -- failed, aborting.\n"
         exit 1
     }
 
@@ -57,7 +57,7 @@ else
     simcargs="'armory=$region,$realm,$selchar' 'calculate_scale_factors=$csf'"
 fi
 
-outfl="$(getdirsafe "wowsimd")/$screenname.html"
+outfl="$(getpath -ds -- "wowsimd")/$screenname.html"
 screen -dmS "$screenname" sh -c "simc $simcargs 'html=$outfl'"
 
 pid="$(
